// Authentication

export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_LOADING = 'USER_LOADING'
export const USER_FAILED = 'USER_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_VERIFIED = 'USER_VERIFIED'


// Shows
export const SHOWS_SUCCESS = 'SHOWS_SUCCESS'
export const SHOWS_LOADING = 'SHOWS_LOADING'
export const SHOWS_FAILED = 'SHOWS_FAILED'


// Orders
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_LOADING = 'ORDERS_LOADING'
export const ORDER_FAILED = 'ORDER_FAILED'


// Films
export const FILMS_SUCCESS = 'FILMS_SUCCESS'
export const FILMS_LOADING = 'FILMS_LOADING'
export const FILMS_FAILED = 'FILMS_FAILED'


// Places
export const PLACES_SUCCESS = 'PLACES_SUCCESS'
export const PLACES_LOADING = 'PLACES_LOADING'
export const PLACES_FAILED = 'PLACES_FAILED'


// Products
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED'


// Products Orders
export const PRODUCTS_ORDERS_SUCCESS = 'PRODUCTS_ORDERS_SUCCESS'
export const PRODUCTS_ORDERS_LOADING = 'PRODUCTS_ORDERS_LOADING'
export const PRODUCTS_ORDERS_FAILED = 'PRODUCTS_ORDERS_FAILED'
